#!/bin/bash
# ═══════════════════════════════════════════════════════════
#  setup-permissions.sh — Set up permissions for monitoring
#  Run with: sudo bash scripts/setup-permissions.sh [username]
# ═══════════════════════════════════════════════════════════

set -e

BOT_USER="${1:-$(whoami)}"

echo "══════════════════════════════════════════════════"
echo "  Linux Server Monitor — Permissions Setup"
echo "  Bot user: $BOT_USER"
echo "══════════════════════════════════════════════════"
echo ""

if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root: sudo bash scripts/setup-permissions.sh [username]"
  exit 1
fi

# ── 0. Detect distro family ──
echo "🔍 Detecting Linux distribution..."
if [ -f /etc/os-release ]; then
  . /etc/os-release
  echo "   Distribution: $PRETTY_NAME"

  case "$ID $ID_LIKE" in
    *debian*|*ubuntu*) DISTRO_FAMILY="debian" ;;
    *rhel*|*fedora*|*centos*) DISTRO_FAMILY="rhel" ;;
    *arch*) DISTRO_FAMILY="arch" ;;
    *suse*) DISTRO_FAMILY="suse" ;;
    *alpine*) DISTRO_FAMILY="alpine" ;;
    *) DISTRO_FAMILY="unknown" ;;
  esac
else
  DISTRO_FAMILY="unknown"
fi
echo "   Family: $DISTRO_FAMILY"

# Resolve log paths per distro
case "$DISTRO_FAMILY" in
  debian)
    AUTH_LOG="/var/log/auth.log"
    SYSLOG="/var/log/syslog"
    ;;
  rhel)
    AUTH_LOG="/var/log/secure"
    SYSLOG="/var/log/messages"
    ;;
  *)
    # Try to detect
    if [ -f /var/log/auth.log ]; then AUTH_LOG="/var/log/auth.log";
    elif [ -f /var/log/secure ]; then AUTH_LOG="/var/log/secure";
    else AUTH_LOG="/var/log/auth.log"; fi

    if [ -f /var/log/syslog ]; then SYSLOG="/var/log/syslog";
    elif [ -f /var/log/messages ]; then SYSLOG="/var/log/messages";
    else SYSLOG="/var/log/syslog"; fi
    ;;
esac
echo "   Auth log: $AUTH_LOG"
echo "   Syslog: $SYSLOG"

# ── 1. RAPL power monitoring (Intel) ──
echo ""
echo "⚡ Setting up RAPL power monitoring..."
if [ -d /sys/class/powercap/intel-rapl ]; then
  chmod -R a+r /sys/class/powercap/intel-rapl/

  # Persistent udev rule
  UDEV_RULE='/etc/udev/rules.d/99-powercap.rules'
  if [ ! -f "$UDEV_RULE" ]; then
    echo 'SUBSYSTEM=="powercap", ACTION=="add", RUN+="/bin/chmod -R a+r /sys/class/powercap/"' > "$UDEV_RULE"
    udevadm control --reload-rules
    udevadm trigger
    echo "   ✅ RAPL permissions set + udev rule created"
  else
    echo "   ✅ RAPL udev rule already exists"
  fi
else
  echo "   ⚠️  RAPL not found. Intel power monitoring won't be available."
fi

# ── 2. Docker group ──
echo ""
echo "🐳 Adding $BOT_USER to docker group..."
if getent group docker > /dev/null 2>&1; then
  usermod -aG docker "$BOT_USER"
  echo "   ✅ $BOT_USER added to docker group"
  echo "   ℹ️  Log out and back in for group change to take effect"
else
  echo "   ⚠️  docker group doesn't exist. Is Docker installed?"
fi

# ── 3. Sudoers for monitoring commands (passwordless) ──
echo ""
echo "🔐 Setting up passwordless sudo for monitoring commands..."
SUDOERS_FILE="/etc/sudoers.d/server-monitor"
cat > "$SUDOERS_FILE" <<EOF
# Server Monitor Bot — passwordless sudo for monitoring commands
# Generated by setup-permissions.sh
# Auth log: $AUTH_LOG | Syslog: $SYSLOG

# ── Log reading ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -c * $AUTH_LOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -c * $SYSLOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -c * /var/log/ufw.log
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* /var/log/nginx/*
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* /var/log/rkhunter.log
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* /var/log/clamav/*
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* $AUTH_LOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* $SYSLOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/tail -* /var/log/ufw.log

# ── Log searching (grep) ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/grep * $AUTH_LOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/grep -c * $AUTH_LOG
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/grep -c * /var/log/ufw.log

# ── Bash (for piped log commands) ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/bash -c sudo grep *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/bash -c sudo tail *

# ── Security tools ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/ufw status *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/fail2ban-client status
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/fail2ban-client status *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/fail2ban-client set * banip *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/fail2ban-client set * unbanip *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/rkhunter --check *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/clamscan *

# ── System info ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/last *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/lastb *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/ls -la /proc/*/exe
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/smartctl *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/hddtemp *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/nvme *

# ── Service management ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl status *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl enable *
$BOT_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl disable *

# ── Nginx ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/nginx -t

# ── Reboot (requires Discord confirmation prompt) ──
$BOT_USER ALL=(ALL) NOPASSWD: /usr/sbin/reboot
EOF

chmod 440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" 2>/dev/null
if [ $? -eq 0 ]; then
  echo "   ✅ Sudoers rules created at $SUDOERS_FILE"
else
  echo "   ❌ Sudoers syntax error! Removing file."
  rm -f "$SUDOERS_FILE"
  exit 1
fi

# ── 4. Ensure data directory exists ──
echo ""
echo "📁 Creating bot data directory..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOT_DIR="$(dirname "$SCRIPT_DIR")"
mkdir -p "$BOT_DIR/data"
chown -R "$BOT_USER:$BOT_USER" "$BOT_DIR/data"
echo "   ✅ data/ directory ready"

# ── Summary ──
echo ""
echo "══════════════════════════════════════════════════"
echo "  ✅ Permissions setup complete!"
echo ""
echo "  Configured:"
echo "    • RAPL power monitoring (Intel)"
echo "    • Docker group membership"
echo "    • Passwordless sudo for monitoring commands"
echo "    • Service management (systemctl)"
echo "    • fail2ban ban/unban"
echo "    • Reboot (with Discord confirmation)"
echo "    • Bot data directory"
echo ""
echo "  ⚠️  IMPORTANT: Log out and back in as '$BOT_USER'"
echo "     for docker group changes to take effect."
echo ""
echo "  ⚠️  The !exec and !sudo commands can only run"
echo "     commands that are whitelisted in this sudoers"
echo "     file. To allow ALL commands (less secure):"
echo "     echo '$BOT_USER ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/server-monitor-full"
echo ""
echo "  Next steps:"
echo "    1. cd $BOT_DIR"
echo "    2. cp .env.example .env"
echo "    3. Edit .env with your Discord bot token"
echo "    4. npm install"
echo "    5. pm2 start ecosystem.config.js"
echo "    6. pm2 save && pm2 startup"
echo "══════════════════════════════════════════════════"
